### ISSUE TITLE
Not working with jdk 11

### ISSUE THREAD

**Issue by GongYiLiao** [QuadStingray/sbt-javafx#3]
I have specify the openjfx dependencies:

```
lazy val javaFXModules = Seq("base", "controls", "fxml", "graphics", "media", "swing", "web")
libraryDependencies ++= javaFXModules.map(m =>
  "org.openjfx" % s"javafx-$m" % "12.0.1" classifier "linux"
)
```
However, when I ran ```sbt javaFxPackage```, I got:

```
$ sbt javaFxPackage
[info] Loading settings for project javafx_test-build from plugins.sbt ...
[info] Loading project definition from /home/gong-yi/Test/jvm/diary/2019/Jul/9/javafx_test/project
[info] Loading settings for project root from build.sbt ...
[info] Set current project to javafx_test (in build file:/home/gong-yi/Test/jvm/diary/2019/Jul/9/javafx_test/)
[warn] Multiple main classes detected.  Run 'show discoveredMainClasses' to see the list
[info] started prepare build
[info] Started Download javafx-ant.jar
[info] Started Download javafx-ant.jar
[info] prepare build finished
[info] build started
[error] java.lang.Exception: JavaHome Directory </usr/lib/jvm/java-11-openjdk-amd64> doesn't exists
[error]         at com.quadstingray.sbt.javafx.SbtTaskManager.workaroundForJavaWithMovedJli(SbtTaskManager.scala:134)
[error]         at com.quadstingray.sbt.javafx.SbtTaskManager.runBuild(SbtTaskManager.scala:88)
[error]         at com.quadstingray.sbt.JavaFxPlugin$autoImport$.$anonfun$javaFxPluginTasks$3(JavaFxPlugin.scala:29)
[error]         at com.quadstingray.sbt.JavaFxPlugin$autoImport$.$anonfun$javaFxPluginTasks$3$adapted(JavaFxPlugin.scala:26)
[error]         at scala.Function1.$anonfun$compose$1(Function1.scala:44)
[error]         at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:40)
[error]         at sbt.std.Transform$$anon$4.work(System.scala:67)
[error]         at sbt.Execute.$anonfun$submit$2(Execute.scala:269)
[error]         at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[error]         at sbt.Execute.work(Execute.scala:278)
[error]         at sbt.Execute.$anonfun$submit$1(Execute.scala:269)
[error]         at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
[error]         at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[error]         at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error]         at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[error]         at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error]         at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[error]         at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[error]         at java.base/java.lang.Thread.run(Thread.java:834)
[error] (Compile / javaFxPackage) java.lang.Exception: JavaHome Directory </usr/lib/jvm/java-11-openjdk-amd64> doesn't exists
[error] Total time: 2 s, completed Jul 10, 2019, 12:40:02 PM
```

Anyway to specify the path that contains openjfx SDK 11+?

**Comment by QuadStingray** [comment]
The problem is your JavaHome Path.
`java.lang.Exception: JavaHome Directory </usr/lib/jvm/java-11-openjdk-amd64> doesn't exists`

Did you specified   `javaFxJavaHome := "/path/to/individual/java/home"` by SBT file or used the system? Can you please check, that the path `/usr/lib/jvm/java-11-openjdk-amd64` is valid?

Which OS do you use?

**Comment by GongYiLiao** [comment]
Actually the directory ```/usr/lib/jvm/java-11-openjdk-amd64``` does exist (```openjdk-11-jdk``` installed via ```apt``` on ```Debian```) and that really confused me.  I also tested other ```openjdk 11``` builds from ```adoptopenjdk.net```  and specify ```javaFxJavaHome``` to here I extract ```openjdk 11``` tar balls (here is ```/home/gong-yi/Downloads/openjdk/11```). However, I got very similar error message again:

```
gong-yi@sid0:~/Test/jvm/diary/2019/Jul/9/javafx_test$ sbt javaFxPackage
[info] Loading settings for project javafx_test-build from plugins.sbt ...
[info] Loading project definition from /home/gong-yi/Test/jvm/diary/2019/Jul/9/javafx_test/project
[info] Loading settings for project root from build.sbt ...
[info] Set current project to javafx_test (in build file:/home/gong-yi/Test/jvm/diary/2019/Jul/9/javafx_test/)
[warn] Multiple main classes detected.  Run 'show discoveredMainClasses' to see the list
[info] started prepare build
[info] Started Download javafx-ant.jar
[info] Started Download javafx-ant.jar
[info] prepare build finished
[info] build started
[error] java.lang.Exception: JavaHome Directory </home/gong-yi/Downloads/openjdk/11> doesn't exists
[error] 	at com.quadstingray.sbt.javafx.SbtTaskManager.workaroundForJavaWithMovedJli(SbtTaskManager.scala:134)
[error] 	at com.quadstingray.sbt.javafx.SbtTaskManager.runBuild(SbtTaskManager.scala:88)
[error] 	at com.quadstingray.sbt.JavaFxPlugin$autoImport$.$anonfun$javaFxPluginTasks$3(JavaFxPlugin.scala:29)
[error] 	at com.quadstingray.sbt.JavaFxPlugin$autoImport$.$anonfun$javaFxPluginTasks$3$adapted(JavaFxPlugin.scala:26)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:44)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:40)
[error] 	at sbt.std.Transform$$anon$4.work(System.scala:67)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:269)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[error] 	at sbt.Execute.work(Execute.scala:278)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:269)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[error] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error] 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[error] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[error] 	at java.base/java.lang.Thread.run(Thread.java:834)
[error] (Compile / javaFxPackage) java.lang.Exception: JavaHome Directory </home/gong-yi/Downloads/openjdk/11> doesn't exists
[error] Total time: 2 s, completed Jul 11, 2019, 12:09:39 PM

``` 
So, it seems that the plugin has a special way to detect a directory and may not work on some system?

**Comment by QuadStingray** [comment]
I have a workaround for Java 12 / 13 on MacOS, that is blocking all builds on Linux. I started building an new version can you please check working? 

I have to write some test on Linux and Windows at the future. 

The new build is currently running and needs 1:30h. You can check: https://travis-ci.org/QuadStingray/sbt-javafx/builds/557323158

New Version: 1.5.1

**Comment by GongYiLiao** [comment]
The build log shows the Linux build was not successful.

**Comment by QuadStingray** [comment]
I started a rebuild and the new Version should work, but in my test setting I have an error with Linux and Java later than 9

https://quadstingray.github.io/sbt-javafx/java/linux.html

When I have more time I'll start an rewrite!

**Comment by Locke** [comment]
I use OpenJDK 11 with Windows, Ubuntu and Debian.

The error mentioned on https://quadstingray.github.io/sbt-javafx/java/linux.html is thrown from the downloaded `ant-javafx.jar` file.

The stack trace comes from the `doValidate` method, which checks on Linux whether the runtime contains either `libjvm.so` or `rt.jar` with this regex defined in in `LinuxAppBundler`: `new String[]{"lib/[^/]+/[^/]+/libjvm.so", "lib/rt.jar"}`.

I compared this to the `WinAppBundler` class. Here the regex is defined as `new String[]{"bin\\\\[^\\\\]+\\\\jvm.dll", "lib\\\\rt.jar"}`.

So I looked into my openjdk installation folders.

On Linux I have the file `lib/server/libjvm.so` which does not match the regex, as that tries to find that file in a deeper subfolder.

On Windows I have the file `bin\server\jvm.dll` which matches and therefore can be found.

I fail to see where you get the `ant-javafx.jar` file from or how you generate it. I believe that the regex should either be `new String[]{"lib/[^/]+/libjvm.so", "lib/rt.jar"}` or `new String[]{"lib/[^/]+/libjvm.so", "lib/[^/]+/[^/]+/libjvm.so", "lib/rt.jar"}`.

In the documentation you write for `javaFxAntPath` "You can set an individual path to ant-javafx.jar" but I don't know where I should get that file from. Maybe there is an updated version available somewhere?

So on my Desktop PC with Debian 10 I could work around that regex: I just copied the file `lib/server/libjvm.so` to `lib/server/DELETEME/libjvm.so` and was able to package / generate the deb file. However I had no time yet to test whether it can be installed and executed, sorry for that..

By the way, on my Windows 10 laptop the packaging fails, apparently I have to install Inno Setup 5 where I had no time to yet. Also, I'm using Ubuntu within WSL on that Windows 10 laptop but the packaging fails too, it seems like a known issue with WSL / fakeroot.
